### ISSUE TITLE
Whether kafka supports kerberos authentication

### ISSUE THREAD

**Issue by slivewo** [benthosdev/benthos#2175] opened 2023-10-19 03:28 UTC

**Comment by mihaitodor** [comment] 2023-10-23 15:12
I'm not very familiar with kerberos authentication, but it looks like there is [some support](https://github.com/linkedin/Burrow/issues/584) in the underlying library which the `kafka` input and output use. I guess those options can be exposed in the Benthos config, but it will require some investigation.

**Comment by mihaitodor** [comment] 2023-11-09 16:49
Duplicate of #877

**Closed by mihaitodor** 2023-11-09 16:49 UTC
Labels: enhancement, needs investigation
