### ISSUE TITLE
benthos panics when flooded by nats messages

### ISSUE THREAD

**Issue by pcosquer** [benthosdev/benthos#1768] opened 2023-02-23 11:14 UTC
Hello,

I'm running benthos with a nats input:

```yaml
input:
  nats:
    urls:
      - nats://localhost:4222
    subject: ">"
pipeline:
  processors:
    - bloblang: |
        root.event = this.catch(deleted())
        root.subject = meta("nats_subject")
output:
  label: ""
  stdout:
    codec: lines
```

Nats is running in a nats container

```
docker run -p 4222:4222 -p 8222:8222 -p 6222:6222 --rm -ti nats:2.9.0 -js 
```

When running this go program, benthos panics

```go
package main

import "github.com/nats-io/nats.go"

func main() {
	nc, _ := nats.Connect(nats.DefaultURL)

	for i := 0; i < 500; i++ {
		nc.Publish("foo", []byte("Hello World"))
	}

	nc.Drain()
	nc.Close()
}
```

```
 ./target/bin/benthos -c config.yaml
INFO Running main config from specified file       @service=benthos path=config.yaml
INFO Receiving NATS messages from subject: >       @service=benthos label="" path=root.input
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x20a3523]

goroutine 76 [running]:
github.com/nats-io/nats%2ego.(*Subscription).ConsumerInfo(0xc000baa4f0?)
        /home/pcosquer/go/pkg/mod/github.com/nats-io/nats.go@v1.15.0/js.go:2386 +0x43
github.com/benthosdev/benthos/v4/internal/impl/nats.errorHandlerOption.func1(0x0?, 0xc0012a56c0, {0x43ce2a0?, 0xc0006f3a40})
        /home/pcosquer/dev/benthos/internal/impl/nats/errors.go:17 +0x174
github.com/nats-io/nats%2ego.(*Conn).processMsg.func2()
        /home/pcosquer/go/pkg/mod/github.com/nats-io/nats.go@v1.15.0/nats.go:2974 +0x36
github.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher(0xc0015b2400)
        /home/pcosquer/go/pkg/mod/github.com/nats-io/nats.go@v1.15.0/nats.go:2571 +0x24
created by github.com/nats-io/nats%2ego.Options.Connect
        /home/pcosquer/go/pkg/mod/github.com/nats-io/nats.go@v1.15.0/nats.go:1293 +0x396
```

My go version:
```
go version go1.19.3 linux/amd64
```

I reproduce this issue on v4.12.0 (official release and local build) and main (commit ee0853261a4e885b712b38c3f5e2cf6c779b4f74), not on v4.11.0.

**Comment by mihaitodor** [comment] 2023-02-23 11:27
Hey @pcosquer! Nice find and thank you for reporting it! Looks like this is a bug in the NATS client libs which has been fixed in https://github.com/nats-io/nats.go/releases/tag/v1.23.0 (see [here](https://github.com/nats-io/nats.go/commit/add6c3994bdc86f329df2b16c5f8a36b29623d0f)).

There's a Benthos PR (#1704) which adds NATS KV support and, also, updates the NATS client libs which should get reviewed soon, but if that needs more attention, I raised #1769 to address this specific issue.

**Comment by mihaitodor** [comment] 2023-02-23 13:37
Oh nooooo 🙈  Thanks for trying it out so quickly! It turns out that a regression bug was introduced in the latest release (v4.12.0) via #1687...

Would you mind giving it another shot with the updated changes from my PR (#1769)?

**Comment by pcosquer** [comment] 2023-02-23 13:44
Your last update fixes the issue :)
Thank you

**Comment by mihaitodor** [comment] 2023-02-23 13:59
Awesome, thank you again! I'll let Ash do the review and merge when he gets a chance

**Comment by Jeffail** [comment] 2023-02-23 15:03
Fix is merged, I'll aim to get a patch release out today.

**Comment by Jeffail** [comment] 2023-02-25 14:15
Release is out

**Closed by Jeffail** 2023-02-25 14:15 UTC
Labels: bug, nats
