### ISSUE TITLE
avro data processing issue

### ISSUE THREAD

**Issue by dhaldergit** [benthosdev/benthos#1864] opened 2023-04-24 08:31 UTC
Hi,

I am trying to read a json data from a source topic (with json) and posting the message into target topic (avro) after basic conversions.
It is failing to decode the amount value with the below error. Please help. 
	  
kafka-json-avro-local  | level=error msg="cannot decode textual record \"com.dhalder.avro.message.input.Deposit\": cannot decode textual bytes: expected initial \"; found: U+0039 '9' for key: \"amount\"" @service=benthos label="" path=root.processor_resources.catch.0

Given Input:
{
   
    "id" : "f977c529-1622-40a5-b160-9897fdafdd0a",
    "amount" : 9,
    "account_id" : "1724",
    "txn_reference_id" : "event_f977c529-1622-40a5-b160-9897fdafdd0a"
  }

The avro target topic schema definition:
{"namespace": "com.dhalder.avro.message.input",
 "type": "record",
  "name": "Deposit",
  "fields": [
    {"name" : "id", "aliases" : ["referenceIdentifier"], "type" : ["null", "string"], "default" : null},
    {"name" : "accid", "aliases" : ["accidentifier"], "type" : "string"},
    {"name" : "code", "aliases" : ["acccode"], "type" : "string"},
    {"name" : "amount",  "aliases" : ["txnamount"], "type" : {"type": "bytes", "logicalType": "decimal", "precision": 17, "scale": 2}}
    
  ]
}

Benthos config:

input:
  label: kafka_json_input
  kafka:
    addresses: ["${BROKER_URL}"]
    topics: 
      - "${INPUT_TOPIC}"
    tls:
      enabled: false
    consumer_group: ${CONSUMER_GRP}
    start_from_oldest: false
output:
  kafka:
    addresses: [ "${OUTPUT_BROKER_URL}" ]
    topic: "${OUTPUT_TOPIC}"
  processors:
    - resource: mappingforresource
    - label: kafka_json_to_avro
      schema_registry_encode:
        url: "${SCHEMA_REGISTRY_URL}"
        subject: "${SCHEMA_IDENTIFIER}"
        refresh_period: 15s
        avro_raw_json: true
    - resource: avroconversioncatch
processor_resources:
  - label: mappingforresource
    bloblang: |
       root.accid = this.account_id
       root.amount = this.amount
       root.id = this.txn_reference_id
       root.code = this.txn_code
      
  - label: avroconversioncatch
    catch:
      - log:
          level: ERROR
          message: ${! error() }
      - bloblang: root = deleted()

**Comment by mihaitodor** [comment] 2023-04-24 21:59
I wonder if this is a duplicate of #1150. Are the messages stored as JSON strings in Kafka?

**Closed** 2023-08-03 12:37 UTC
Labels: question, needs more info
