### ISSUE TITLE
[Bug] Upsert setting does't work for mongodb output plugin

### ISSUE THREAD

**Issue by EverGreen5455** [benthosdev/benthos#1984] opened 2023-06-29 08:28 UTC
`upsert` setting is always false
```yaml
# Config example
output:
  mongodb:
    ...
    operation: replace-one
    upsert: true
    ...
```

https://github.com/benthosdev/benthos/blob/5225e1a58a1bf102e05d6285e62df24591fb757e/internal/impl/mongodb/common.go#L337-L341

Affected version: >=4.17.0

**Comment by Jeffail** [comment] 2023-06-29 08:52
Thanks for raising this @EverGreen5455, looks like a regression introduced to the output but also a pre-existing bug with the processor. This should be fixed with: https://github.com/benthosdev/benthos/commit/c93d4ff119b4cf870e8a6ae383db5584263226cd, I'll aim to get a release out this week.

**Comment by Jeffail** [comment] 2023-07-05 08:18
Release is out so closing

**Closed by Jeffail** 2023-07-05 08:18 UTC
Labels: bug, processors, outputs
