### ISSUE TITLE
Test failing for matching object metadata

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1791] opened 2023-03-07 00:45 UTC
Given the following example config:

benthos.yml
```yml
input:
  stdin:
    codec: lines
pipeline:
  processors:
    - mapping: |
        meta foo = { "bar": "hello" }
output:
  stdout:
    codec: lines
```

benthos_benthos_test.yml

```yml
tests:
  - name: Should not fail
    target_processors: "/pipeline/processors"
    mocks:
    input_batch:
      - content: hello
    output_batches:
      - - metadata_equals:
            foo: { "bar": "hello" }
```

Running 

```shell
$ benthos test benthos.yml
Test 'benthos.yml' failed

Failures:

--- benthos.yml ---

Should not fail [line 2]:
batch 0 message 0: metadata_equals: metadata key 'foo' mismatch
  expected: map[bar:hello]
  received: map[bar:hello]
```

Notice the content is the same, althought the test fails anyway

**Comment by peczenyj** [comment] 2023-03-07 09:49
I found the root cause:

on internal/cli/test/conditions.go

```golang
		case "metadata_equals":
			val := MetadataEqualsCondition{}
			if err := v.Decode(&val); err != nil {
				return fmt.Errorf("line %v: %v", v.Line, err)
			}
			cond = val

```

somehow it decodes something like

```golang
val := MetadataEqualsCondition{
   "foo": MetadataEqualsCondition { "bar", "hello" }, 
}
```

where `MetadataEqualsCondition` is `map[string]any` and inside some functions that sanitize the types used on certain tests and assertions, the swich case does no catch the type as `map[string]any`

an easy fix should be, you can submit a Pull Request if you can add a unit test that can trigger this issue

```golang
		case "metadata_equals":
			var val map[string]any
			if err := v.Decode(&val); err != nil {
				return fmt.Errorf("line %v: %v", v.Line, err)
			}
			cond = MetadataEqualsCondition(val)
		default:
```


Regards

**Comment by Jeffail** [comment] 2023-03-07 10:41
Hey @natenho, thanks for raising this, and thanks for the investigation @peczenyj, got it reproduced and fixed: https://github.com/benthosdev/benthos/commit/c4e3d420f043e0e919327b1894899419a62cf5ad

**Comment by Jeffail** [comment] 2023-03-07 10:42
The next release will be in a week or so, closing for now.

**Closed by Jeffail** 2023-03-07 10:42 UTC
Labels: bug, testing
